# Generated by Django 4.2.15 on 2024-08-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='price',
            new_name='description',
        ),
    ]
